# Generated by Django 2.2.9 on 2020-01-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64)),
                ('confirmations', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('height', models.BigIntegerField()),
                ('numOfTrx', models.IntegerField()),
                ('difficulty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('merkleRoot', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('bits', models.BigIntegerField()),
                ('weight', models.BigIntegerField()),
                ('size', models.BigIntegerField()),
                ('nonce', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('size', models.BigIntegerField()),
                ('weight', models.BigIntegerField()),
                ('blockHash', models.CharField(max_length=64)),
                ('confirmations', models.IntegerField()),
            ],
        ),
    ]
